version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextuser
    restart: always
    env_file:
      - .env.local
    ports:
      - "3010:3000"
