// eslint-disable-next-line import/no-anonymous-default-export
export default {
	services: [
		"Logo Design",
		"Brand Style Guides",
		"Fonts & Typography",
		"Website Design",
		"App Design",
		"UX Design",
		"Landing Page Design",
		"Icon Design",
		"Illustration",
		"AI Artists",
		"Children's Book Illustration",
		"Portraits & Caricatures",
		"Storyboards",
		"Image Editing",
		"Presentation Design",
		"Infographic Design",
		"Vector Tracing",
		"Flyer Design",
		"Brochure Design",
		"Poster Design",
		"Catalog Design",
		"Menu Design",
		"Invitation Design",
		"Book Design",
		"Book Covers",
		"Album Cover Design",
		"Podcast Cover Art",
		"3D Landscape",
		"Social Media Design",
		"Thumbnails Design",
		"Email Design",
		"Banners Design",
		"T-Shirts Design",
		"SEO",
		"Search Engine Marketing",
		"E-Commerce SEO",
		"Video SEO",
		"Social Media Marketing",
		"Paid Social Media",
		"Video Marketing",
		"Email Marketing",
		"Display Advertisement",
		"Web Analytics",
		"Video Editing",
		"Visual Effects",
		"Intro & Outro Videos",
		"Video Templates Editing",
		"Subtitles & Captions",
		"Rigging",
		"Lottie & Web Animation",
		"Video Ads & Commercials",
		"Social Media Videos",
		"Slideshow Videos",
		"Corporate Videos",
		"Real Estate Promos",
		"3D Product Animation",
		"App & Website Previews",
		"Article to Video",
		"Website Development",
		"Website Maintenance",
		"Website Customization",
		"WordPress",
		"Shopify",
		"Wix",
		"Webflow",
		"Custom Websites",
		"Software Development",
		"Mobile Apps",
		"Web Applications",
		"Chatbots Development",
		"Data Formatting & Cleaning",
		"Data Mining & Scraping",
		"Database Design & ERD",
		"Data Analytics & Visualization",
	],
	whatWeDo: [
		{
			title: "Brand Strategy",
			content:
				"We make your company recognizable and memorable against the background of competitors. Branding for us is not only the development of a logo, but a complete representation of the company.",
			to: "#",
		},
		{
			title: "Interface Design",
			content:
				"We consider user interaction with the interface. We pay special attention to hypothesis testing and prototyping, only the most successful solutions reach visualization.",
			to: "#",
		},
		{
			title: "Website Design",
			content:
				"We create a functional design in the style of aesthetics of minimalism. We add micro animations to sites that give a emotional response from users. Our sites are always adapt to all types of devices.",
			to: "#",
		},
		{
			title: "Mobile App Design",
			content:
				"We create applications of any complexity for iOS, Android. Thanks to the built-in interaction logic visual part, our applications are pleasant and convenient to use, which ultimately brings high profit.",
			to: "#",
		},
		{
			title: "Video & Motion",
			content:
				"We create applications of any complexity for iOS, Android. Thanks to the built-in interaction logic visual part, our applications are pleasant and convenient to use, which ultimately brings high profit.",
			to: "#",
		},
	],
};
